---

- hosts: all
  become: true
  tasks:

  - name: install httpd and php package
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Rocky"]
