---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["Rocky"]

- hosts: web_servers 
  become: true
  tasks:
  - name: install apache and php for rocky os server
    tags: centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Rocky"
  - name: copy html file for site
    tags: apache,httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks: 

  - name: install mariadb server on Rocky
    tags: db,centos,mriadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "Rocky"

- hosts: file_servers
  become: true
  tasks: 
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
